---
- hosts: dev
  gather_facts: true
  vars:
    region: us-west-2
  tasks:
   - name: Touch a file (creates if not present, updates modification time if present)
     win_file:
        region: "{{ region }}"
        AWS_ACCESS_KEY_ID: "{{ access }}"
        AWS_SECRET_ACCESS_KEY: "{{ secret }}"
        path: C:\Users\hari.txt
        state: touch
